name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fluentd-kafka:v1.0
    - name: Run docker-compose
      run: docker-compose up -d

    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content

    - name: setup python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: '3.10' # install the python version needed

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/test-scripts/requirements.txt

    - name: test message
      run: |
        export MESSAGE=$(python .github/workflows/test-scripts/random-message.py)
        echo $MESSAGE
        export KAFDROP_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' fluentd-kafka_kafdrop_1)
        echo $KAFDROP_IP
        logger -n $KAFDROP_IP -P 5140 -d "$MESSAGE"
        #python .github/workflows/test-scripts/test-message.py $MESSAGE $(hostname)
